.TH deepin-terminal-gtk 1 "August 21, 2017" "Deepin"

.SH NAME
deepin\-terminal\-gtk \- Deepin terminal emulator application

.SH SYNOPSIS
.B deepin-terminal-gtk
.RI [ OPTION... ]

.SH DESCRIPTION
Deepin Terminal is a terminal emulator with simple interface, rich and powerful functions created by Deepin Technology. You can instantly start and close Deepin Terminal smoothly like normal file window, allowing you to input commands with facility and no distractions. Let's try the Quake mode, browse webs while inputting commands. When there are multiple tasks, you can add tabs in terminal to create more workspaces like in the browser or split the workspace into multiple windows. It's a piece of cake to upload and download files with remote management. More powerful functions are waiting for you to explore!

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help options
.TP
.B \-\-version 
Display version
.TP
.BR \-w ", " \-\-work\-directory
Set the terminal startup directory
.TP
.BR \-m ", " \-\-window\-mode
Set the terminal window mode (normal, maximize, fullscreen)
.TP
.BR \-e ", " \-\-execute
Run a program in the terminal
.TP
.BR \-x ", " \-\-execute 
Run a program in the terminal
.TP
.BR \-q ", " \-\-quake\-mode
Quake mode
.TP
.BR \-l ", " \-\-load\-theme
Load theme

.SH AUTHOR
.B deepin-terminal-gtk
is written by Deepin Technology Co., Ltd.

This manual page was written by
.MT zouyoo@\:outlook.com
GengYu Rao
.ME
for the Debian project (but may be used by others).
